BlogProject.Web/Areas/Admin/Controllers/AuthorizeController.cs
using BlogProject.DAL.Entities;
using BlogProject.DAL.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorizeController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public AuthorizeController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }


        [AllowAnonymous]    //Authorize işleminden hariç tutmak için.
        [HttpPost]
        //public async Task<IActionResult> Login(UserLoginVM userLoginVM)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View();
        //    }

        //    var user = await _userManager.FindByEmailAsync(userLoginVM.Email);
        //    if (user == null) 
        //    {
        //        ModelState.AddModelError("", "Email adresininiz veya şifreniz yanlıştır.");
        //        return View();
        //    }

        //    var result = await _signInManager.PasswordSignInAsync(user, userLoginVM.Password, userLoginVM.RememberMe, false);
        //    if (!result.Succeeded)
        //    {
        //        ModelState.AddModelError("", "Email adresininiz veya şifreniz yanlıştır.");
        //        return View();
        //    }

        //    return RedirectToAction("Index", "Home", new { Area = "" });
        //}

        public async Task<IActionResult> Login(UserLoginVM userLoginVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                var user = await _userManager.FindByEmailAsync(userLoginVM.Email);
                if (user == null)
                {
                    ModelState.AddModelError("", "Email adresiniz veya şifreniz yanlıştır.");
                    return View();
                }

                var result = await _signInManager.PasswordSignInAsync(user, userLoginVM.Password, userLoginVM.RememberMe, false);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Email adresiniz veya şifreniz yanlıştır.");
                    return View();
                }

                return RedirectToAction("Index", "Home", new { Area = "" });
            }
            catch (Exception ex)
            {
                // Loglama yapılabilir
                ModelState.AddModelError("", "Beklenmeyen bir hata oluştu. Lütfen tekrar deneyiniz.");
                return View();
            }
        }



        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Logout() 
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home", new { Area = "" });
        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> AccessDenied()     //Rol bazlı erişim engeline takılırsak bu sayfaya yönlendirecek.
        {
            return View();
        }
    }
}

BlogProject.Web/Controllers/ArticleController.cs
using AutoMapper;
using BlogProject.BLL.Services.Abstract;
using BlogProject.BLL.Services.Concrete;
using BlogProject.DAL.Entities;
using BlogProject.DAL.ViewModels.Articles;
using BlogProject.DAL.ViewModels.Categories;
using BlogProject.DAL.ViewModels.Users;
using BlogProject.Web.Consts;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.Web.Controllers
{
    [Authorize(Roles = $"{RoleConsts.Admin}, {RoleConsts.Author}")]
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;
        private readonly IValidator<Article> _validator;
        private readonly IValidator<Category> _cValidator;

        public ArticleController(IArticleService articleService, ICategoryService categoryService, IMapper mapper, IValidator<Article> validator, IValidator<Category> cValidator)
        {
            _articleService = articleService;
            _categoryService = categoryService;
            _mapper = mapper;
            _validator = validator;
            _cValidator = cValidator;
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var categories = await _categoryService.GetAllCategoriesNonDeleted();
            return View(new ArticleCreateVM { CategoryVMs = categories });
        }


        [HttpPost]
        public async Task<IActionResult> Create(ArticleCreateVM articleCreateVM)
        {
            if (articleCreateVM.Photo == null)
            {
                ModelState.AddModelError("", "Resim yüklemeden makale yayımlayamazsınız.");
                var categories = await _categoryService.GetAllCategoriesNonDeleted();
                return View(new ArticleCreateVM { CategoryVMs = categories });
            }

            var map = _mapper.Map<Article>(articleCreateVM);    //VM'i Article'a çeviriyoruz. Buradaki birbirine çevrilen nesneleri AutoMapper/Mapping class'ına da eklememiz gerekir.
            var result = await _validator.ValidateAsync(map);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                //Validasyonlardan bir hata gelirse Kategori combobox'ının içinin yine dolu gelmesi için bu kodları yine yazıyoruz.
                var categories = await _categoryService.GetAllCategoriesNonDeleted();
                return View(new ArticleCreateVM { CategoryVMs = categories });
            }

            await _articleService.CreateArticle(articleCreateVM);
            return RedirectToAction("Index", "Home", new { Area = "" });
        }


        public async Task<IActionResult> AddWithAjax([FromBody] CategoryCreateVM categoryCreateVM)
        {
            var map = _mapper.Map<Category>(categoryCreateVM);
            var result = await _cValidator.ValidateAsync(map);

            if (!result.IsValid)
            {
                return Json(result.Errors.First().ErrorMessage);
            }

            await _categoryService.CreatedCategory(categoryCreateVM);
            string categoryName = categoryCreateVM.Name;
            return Json(categoryName);
        }
    }
}

BlogProject.Web/Controllers/UserController.cs
using BlogProject.BLL.Services.Abstract;
using BlogProject.BLL.Services.Concrete;
using BlogProject.DAL.ViewModels.Users;
using BlogProject.Web.Consts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.Web.Controllers
{
    [Authorize(Roles = $"{RoleConsts.Admin}, {RoleConsts.Author}")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }


        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var profile = await _userService.GetUserProfile();
            return View(profile);
        }

        [HttpPost]
        public async Task<IActionResult> Profile(UserProfileVM userProfileVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (userProfileVM.CurrentPassword == null)
            {
                ModelState.AddModelError("", "Profilinizi güncellemek için mevcut şifrenizi girmek zorundasınız.");
                var profile = await _userService.GetUserProfile();
                return View(profile);
            }

            var result = await _userService.UserProfileUpdate(userProfileVM);
            if (result)
            {
                return RedirectToAction("Index", "Home", new { Area = "" });
            }
            else
            {
                var profile = await _userService.GetUserProfile();
                return View(profile);
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            var result = await _userService.DeleteUser(id);
            if (result.Succeeded)
            {
                return RedirectToAction("About", "Home", new { Area = "" });
            }
            else
            {
                result.AddToIdentityModelState(this.ModelState);
            }

            return NotFound();
        }
    }
}

BlogProject.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Blog</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogProject.Web.styles.css" asp-append-version="true" />

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/stand-blog/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/stand-blog/assets/css/templatemo-stand-blog.css">
    <link rel="stylesheet" href="assets/css/owl.css">

    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Custom Styles -->
    <style>
        body {
            color: black;
            font-family: 'Cascadia Mono';
        }

        label {
            color: darkorange;
            font-weight: bold;
        }

        input[type=text],
        input[type=file],
        input[type=email],
        textarea[type=text],
        select[class=form-control] {
            border-style: solid;
            border-color: black;
            border-width: 2px;
        }

        h5 {
            font-weight: bold;
        }

        footer {
            background-color: #cfe2f3;
            padding: 20px 0;
            text-align: center;
        }

            footer p {
                color: darkorange;
            }

        /* Navbar Styles */
        .navbar {
            background-color: #cfe2f3; /* Arka plan rengi */
            padding: 20px 0; /* Navbar içeriği etrafındaki dolgu */
        }

        .navbar-brand {
            color: black; /* Navbar marka metni rengi */
            font-size: 24px; /* Navbar marka metni boyutu */
        }

        .navbar-nav {
            margin-left: auto; /* Navbar menüsünü sağa hizalama */
        }

        .nav-item {
            margin-left: 20px; /* Navbar öğeleri arasındaki boşluk */
        }

        .nav-link {
            color: black !important; /* Navbar öğelerinin metin rengi */
            font-size: 18px; /* Navbar öğelerinin metin boyutu */
        }

        .navbar-toggler {
            border-color: #fff; /* Navbar açılır menü düğmesi rengi */
        }

        .navbar-toggler-icon {
            background-color: #fff; /* Navbar açılır menü simgesi rengi */
        }
    </style>
</head>
<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- Header -->
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container justify-content-center">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" alt="Logo" style="height: 40px; margin-right: 10px;">
                    ANASAYFA
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                                <i class='bx bxs-hard-hat'></i> Admin Paneli
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Article" asp-action="Create">
                                <i class='bx bx-book'></i> Makale Yaz
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Profile">
                                <i class='bx bxs-user-detail'></i> Profil Bilgilerim
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Authorize" asp-action="Logout">
                                <i class='bx bxs-user-x'></i> Çıkış Yap
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text">
        <div class="container-fluid">
            <!-- Banner Content Goes Here -->
        </div>
    </div>
    <!-- Banner Ends Here -->

    <div style="height:50px;"></div>

    @RenderBody()
    <footer style="background-color: #343a40; padding: 20px 0;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright-text" style="color: #ffffff; text-align: center;">
                        <p>Copyright 2024 Designed By Mahmut Taylan</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/stand-blog/vendor/jquery/jquery.min.js"></script>
    <script src="~/stand-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Additional Scripts -->
    <script src="~/stand-blog/assets/js/custom.js"></script>
    <script src="~/stand-blog/assets/js/owl.js"></script>
    <script src="~/stand-blog/assets/js/slick.js"></script>
    <script src="~/stand-blog/assets/js/isotope.js"></script>
    <script src="~/stand-blog/assets/js/accordions.js"></script>

    <!-- jQuery and Bootstrap Bundle -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- DataTables -->
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.3/js/dataTables.buttons.min.js" crossorigin="anonymous"></script>
    <script language="text/Javascript">
        cleared[0] = cleared[1] = cleared[2] = 0;
        function clearField(t) {
            if (!cleared[t.id]) {
                cleared[t.id] = 1;
                t.value = '';
                t.style.color = '#fff';
            }
        }
    </script>

    <!-- Additional Scripts End -->
    <!-- Section for Page Specific Scripts -->
    @await RenderSectionAsync("Scripts", false);

</body>
</html>