BlogProject.Web/Areas/Admin/Controllers/AuthorizeController.cs
using BlogProject.DAL.Entities;
using BlogProject.DAL.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BlogProject.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorizeController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public AuthorizeController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }


        [AllowAnonymous]    //Authorize işleminden hariç tutmak için.
        [HttpPost]
        //public async Task<IActionResult> Login(UserLoginVM userLoginVM)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View();
        //    }

        //    var user = await _userManager.FindByEmailAsync(userLoginVM.Email);
        //    if (user == null) 
        //    {
        //        ModelState.AddModelError("", "Email adresininiz veya şifreniz yanlıştır.");
        //        return View();
        //    }

        //    var result = await _signInManager.PasswordSignInAsync(user, userLoginVM.Password, userLoginVM.RememberMe, false);
        //    if (!result.Succeeded)
        //    {
        //        ModelState.AddModelError("", "Email adresininiz veya şifreniz yanlıştır.");
        //        return View();
        //    }

        //    return RedirectToAction("Index", "Home", new { Area = "" });
        //}

        public async Task<IActionResult> Login(UserLoginVM userLoginVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                var user = await _userManager.FindByEmailAsync(userLoginVM.Email);
                if (user == null)
                {
                    ModelState.AddModelError("", "Email adresiniz veya şifreniz yanlıştır.");
                    return View();
                }

                var result = await _signInManager.PasswordSignInAsync(user, userLoginVM.Password, userLoginVM.RememberMe, false);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Email adresiniz veya şifreniz yanlıştır.");
                    return View();
                }

                return RedirectToAction("Index", "Home", new { Area = "" });
            }
            catch (Exception ex)
            {
                // Loglama yapılabilir
                ModelState.AddModelError("", "Beklenmeyen bir hata oluştu. Lütfen tekrar deneyiniz.");
                return View();
            }
        }



        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Logout() 
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home", new { Area = "" });
        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> AccessDenied()     //Rol bazlı erişim engeline takılırsak bu sayfaya yönlendirecek.
        {
            return View();
        }
    }
}

BlogProject.Web/Controllers/RegisterController.cs
using BlogProject.BLL.Services.Concrete;
using BlogProject.DAL.Concrete.Context;
using BlogProject.DAL.Entities;
using BlogProject.DAL.UnitOfWorks;
using BlogProject.DAL.ViewModels.Users;
using FluentValidation;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using System.Data;

namespace BlogProject.Web.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IValidator<AppUser> _validator;
        private readonly AppIdentityContext _appIdentityContext;

        public RegisterController(UserManager<AppUser> userManager, IValidator<AppUser> validator, AppIdentityContext appIdentityContext)
        {
            _userManager = userManager;
            _validator = validator;
            _appIdentityContext = appIdentityContext;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        //public async Task<IActionResult> Register(UserRegisterVM userRegisterVM)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(userRegisterVM);
        //    }

        //    Random rnd = new Random();      //mail aktivasyonu için kod ürettik.
        //    int code = rnd.Next(100000, 1000000);

        //    AppUser user = new AppUser() 
        //    { 
        //        FirstName = userRegisterVM.FirstName,
        //        LastName = userRegisterVM.LastName,
        //        UserName = userRegisterVM.Email,
        //        Email = userRegisterVM.Email,
        //        PhoneNumber = userRegisterVM.PhoneNumber,
        //        ConfirmCode = code,
        //        About = userRegisterVM.About
        //    };

        //    if (userRegisterVM.ConfirmPassword == null || userRegisterVM.ConfirmPassword != userRegisterVM.Password)
        //    {
        //        ModelState.AddModelError("", "Doğrulama şifresini yanlış girdiniz.");
        //        return View(userRegisterVM);
        //    }

        //    var validation = await _validator.ValidateAsync(user);
        //    var result = await _userManager.CreateAsync(user, string.IsNullOrEmpty(userRegisterVM.Password) ? "" : userRegisterVM.Password);    //Şifreyi girmeyince hata fırlatıyordu. Ternary If kullanarak şifre boşsa null getirdik. Böylece validasyon hatasına gittik.

        //    if (!result.Succeeded)
        //    {
        //        result.AddToIdentityModelState(this.ModelState);
        //        validation.AddToModelState(this.ModelState);
        //        return View(userRegisterVM);
        //    }

        //    IdentityUserRole<int> role = new IdentityUserRole<int>()    //Üyeye default Author rolü atamak için.
        //    {
        //        UserId =user.Id,
        //        RoleId = userRegisterVM.RoleId
        //    };
        //    _appIdentityContext.UserRoles.Add(role);
        //    _appIdentityContext.SaveChanges();

        //    MimeMessage mimeMessage = new MimeMessage();
        //    MailboxAddress mailboxAddressFrom = new MailboxAddress("BlogProject Admin", "mahmuttaylan3@gmail.com");
        //    MailboxAddress mailboxAddressTo = new MailboxAddress("User", user.Email);
        //    mimeMessage.From.Add(mailboxAddressFrom);
        //    mimeMessage.To.Add(mailboxAddressTo);

        //    var bodyBuilder = new BodyBuilder();
        //    bodyBuilder.TextBody = $"Kayıt işlemini gerçekleştirmek için onay kodunuz: {code}";
        //    mimeMessage.Body = bodyBuilder.ToMessageBody();
        //    mimeMessage.Subject = "BlogProject Üyelik Onay Kodu";

        //    SmtpClient smtpClient = new SmtpClient();

        //    //Gmail Türkiye kodu = 587
        //    smtpClient.Connect("smtp.gmail.com", 587, false);

        //    //Gmail'i aç. ayarlara gel. Güvenlik ayarları çift taraflı doğrulama açık olacak. arama kutusuna uygulama şifreleri yaz. gelen ekranda bir cihaz tanımla çıkan şifreyi buraya yapıştır.
        //    smtpClient.Authenticate("mahmuttaylan3@gmail.com", "cnig febp nlji rkub");
        //    smtpClient.Send(mimeMessage);
        //    smtpClient.Disconnect(true);

        //    TempData["Mail"] = userRegisterVM.Email;

        //    return RedirectToAction("Index", "ConfirmMail");
        //}

        public async Task<IActionResult> Register(UserRegisterVM userRegisterVM)
        {
            if (!ModelState.IsValid)
            {
                return View(userRegisterVM);
            }

            if (userRegisterVM.ConfirmPassword == null || userRegisterVM.ConfirmPassword != userRegisterVM.Password)
            {
                ModelState.AddModelError("", "Tekrar şifresini yanlış girdiniz.");
                return View(userRegisterVM);
            }

            try
            {
                Random rnd = new Random();
                int code = rnd.Next(100000, 1000000);

                AppUser user = new AppUser()
                {
                    FirstName = userRegisterVM.FirstName,
                    LastName = userRegisterVM.LastName,
                    UserName = userRegisterVM.Email,
                    Email = userRegisterVM.Email,
                    PhoneNumber = userRegisterVM.PhoneNumber,
                    ConfirmCode = code,
                    About = userRegisterVM.About
                };

                var validation = await _validator.ValidateAsync(user);
                var result = await _userManager.CreateAsync(user, string.IsNullOrEmpty(userRegisterVM.Password) ? "" : userRegisterVM.Password);

                if (!result.Succeeded)
                {
                    result.AddToIdentityModelState(this.ModelState);
                    validation.AddToModelState(this.ModelState);
                    return View(userRegisterVM);
                }

                IdentityUserRole<int> role = new IdentityUserRole<int>()
                {
                    UserId = user.Id,
                    RoleId = userRegisterVM.RoleId
                };

                _appIdentityContext.UserRoles.Add(role);
                _appIdentityContext.SaveChanges();

                try
                {
                    MimeMessage mimeMessage = new MimeMessage();
                    MailboxAddress mailboxAddressFrom = new MailboxAddress("BlogProject Admin", "mahmuttaylan3@gmail.com");
                    MailboxAddress mailboxAddressTo = new MailboxAddress("User", user.Email);
                    mimeMessage.From.Add(mailboxAddressFrom);
                    mimeMessage.To.Add(mailboxAddressTo);

                    var bodyBuilder = new BodyBuilder();
                    bodyBuilder.TextBody = $"Kayıt işlemini gerçekleştirmek için onay kodunuz: {code}";
                    mimeMessage.Body = bodyBuilder.ToMessageBody();
                    mimeMessage.Subject = "BlogProject Üyelik Onay Kodu";

                    using (SmtpClient smtpClient = new SmtpClient())
                    {
                        smtpClient.Connect("smtp.gmail.com", 587, false);
                        smtpClient.Authenticate("mahmuttaylan3@gmail.com", "cnig febp nlji rkub");
                        smtpClient.Send(mimeMessage);
                        smtpClient.Disconnect(true);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Mail gönderme işlemi başarısız oldu. Lütfen daha sonra tekrar deneyiniz.");
                    // Hata loglama eklenebilir.
                }

                TempData["Mail"] = userRegisterVM.Email;

                return RedirectToAction("Index", "ConfirmMail");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Kayıt işlemi sırasında bir hata oluştu. Lütfen tekrar deneyiniz.");
                // Hata loglama eklenebilir.
                return View(userRegisterVM);
            }
        }

    }
}

BlogProject.Web/Views/Register/Register.cshtml
@model UserRegisterVM

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Kayıt Ol</title>

    <meta name="description" content="Most Powerful & Comprehensive Bootstrap 5 HTML Admin Dashboard Template built for developers!" />
    <meta name="keywords" content="dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5">
    <link rel="icon" type="image/x-icon" href="~/sneat/assets/img/favicon/favicon.ico" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/sneat/assets/vendor/fonts/boxicons.css" />
    <link rel="stylesheet" href="~/sneat/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/sneat/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/sneat/assets/css/demo.css" />
    <link rel="stylesheet" href="~/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    <link rel="stylesheet" href="~/sneat/assets/vendor/css/pages/page-auth.css">
    <style>
        .navbar-nav {
            margin: 0 auto;
        }

        .nav-link {
            color: white !important;
            font-weight: bold;
            border: 2px solid white;
            border-radius: 5px;
            padding: 5px 10px;
            margin: 0 10px;
        }

        .nav-link:hover {
            color: yellow !important;
            border-color: yellow;
        }

        body {
            background-color: #f8f9fa; /* Arka plan rengi */
            font-family: 'Public Sans', sans-serif;
        }

        .authentication-wrapper {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 80vh; /* Kartın sayfanın yüksekliğinin %80'inde olmasını istiyorsanız bu değeri ayarlayabilirsiniz */
            margin-top: 50px; /* Navbar ile kart arasında boşluk bırakmak için */
        }

        .card {
            border: 1px solid #dee2e6;
            border-radius: 0.75rem;
            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
            background-color: #03C3EC;
            width: 600px;
            max-width: 100%;
            padding: 2rem;
        }

        .form-label {
            font-weight: bold;
        }
    </style>
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-info fixed-top"> <!-- Navbar'ın sayfanın üstünde sabit durması için fixed-top sınıfını ekledim -->
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("About", "Home")">Hakkımızda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Login", "Authorize", new { area = "Admin" })">Giriş Yap</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="row mb-3">
        <div class="col-md-12">
            <div class="authentication-wrapper" style="display: flex; justify-content: center;">
                <div class="authentication-inner" style="width: 600px;">
                    <!-- Kartın genişliğini ayarlamak için width: 600px; ekledik -->
                    <!-- Register Card -->
                    <div class="card">
                        <div class="card-body">
                            <h4 class="text-center mb-4">KAYIT OL</h4>
                            <form asp-controller="Register" asp-action="Register" id="formAuthentication" class="mb-3" method="post">
                                <div asp-validation-summary="All" style="color:red"></div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <label asp-for="FirstName" class="form-label" for="firstname">İsim</label>
                                        <input asp-for="FirstName" type="text" class="form-control" id="firstname" name="firstname" placeholder="İsim" autofocus>
                                    </div>
                                    <div class="col-md-6">
                                        <label asp-for="LastName" class="form-label" for="lastname">Soyisim</label>
                                        <input asp-for="LastName" type="text" class="form-control" id="lastname" name="lastname" placeholder="Soyisim">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <label asp-for="PhoneNumber" class="form-label" for="phoneNumber">Telefon Numarası</label>
                                        <input asp-for="PhoneNumber" type="text" class="form-control" id="phoneNumber" name="phoneNumber" placeholder="Telefon Numarası" style="width: 100%;">
                                    </div>
                                    <div class="col-md-6">
                                        <label asp-for="Email" class="form-label" for="email">Email</label>
                                        <input asp-for="Email" type="text" class="form-control" id="email" name="email" placeholder="Email" style="width: 100%;">
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label asp-for="About" class="form-label">Hakkında</label>
                                    <textarea asp-for="About" class="form-control" placeholder="Hakkında" style="width: 100%;"></textarea>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <label asp-for="Password" class="form-label" for="password">Şifre</label>
                                        <input asp-for="Password" type="password" class="form-control" id="password" name="password" placeholder="Şifre" style="width: 100%;">
                                    </div>
                                    <div class="col-md-6">
                                        <label asp-for="ConfirmPassword" class="form-label" for="confirmPassword">Şifre Tekrarı</label>
                                        <input asp-for="ConfirmPassword" type="password" class="form-control" id="confirmPassword" name="confirmPassword" placeholder="Şifre Tekrarı" style="width: 100%;">
                                    </div>
                                </div>
                                <button class="btn btn-primary w-100" style="background-color:black">Kaydol</button>
                            </form>
                        </div>
                    </div>
                    <!-- Register Card -->
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-dark text-white">
        <div class="container">
            <span class="text-muted">© 2024 Blog Sitemiz. Tüm hakları saklıdır.</span>
        </div>
    </footer>
    <!-- Content -->
    
    <!-- / Content -->
    <!-- Core JS -->
    <script src="~/sneat/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/sneat/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/sneat/assets/vendor/js/bootstrap.js"></script>
    <script src="~/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/sneat/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/sneat/assets/js/main.js"></script>

</body>

</html>